name: Parser

on:
  schedule:
    - cron: '*/5 * * * *'  # Запуск каждые 5 минут

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install playwright
          playwright install firefox
      - name: Run script
        run: python main.py
      - name: Commit data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output.txt
          git commit -m "Update data"
          git push
